# Generated by Django 4.0.1 on 2022-01-13 21:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('especies', '0004_alter_especies_options'),
        ('piscinas', '0001_initial'),
        ('contactos', '0003_empresa_codigo_empresa_proveedor_aprobado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocRegistro',
            fields=[
                ('no_doc_registro', models.CharField(max_length=14, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='nomatch', message='Formato de código no válido', regex='\\d{4}.\\d{9}')], verbose_name='Número documento Registro')),
                ('fecha_recoleccion', models.DateField(verbose_name='Fecha recolección')),
                ('destino', models.CharField(default='MercaMaris Nº RGSEAA: 12.021608/C', max_length=100, verbose_name='Destino')),
                ('zona_gal', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre zona GAL')),
                ('zona_biotoxina', models.CharField(max_length=100, verbose_name='Nombre zona biotoxina')),
                ('c_sanitaria', models.CharField(max_length=1, verbose_name='Calificación sanitaria')),
                ('verificacion_toxinas', models.BooleanField(blank=True, null=True, verbose_name='Zona biotoxinas abierta?')),
                ('cliente', models.ForeignKey(limit_choices_to={'cliente': True}, on_delete=django.db.models.deletion.PROTECT, related_name='cliente_doc_reg', to='contactos.empresa')),
                ('n_recolector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recolector', to='contactos.proveedor')),
            ],
            options={
                'verbose_name': 'Documento de registro',
                'verbose_name_plural': 'Documentos de registro',
                'ordering': ['no_doc_registro'],
            },
        ),
        migrations.CreateModel(
            name='EntradaBivalvosDepuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(editable=False, max_length=40, verbose_name='Lote')),
                ('cantidad_recibida', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad recibida')),
                ('fecha_hora_entrada', models.DateTimeField(verbose_name='Fecha y hora entrada')),
                ('ria_pais', models.CharField(max_length=100, verbose_name='Ría/País')),
                ('m_produccion', models.CharField(blank=True, choices=[('capturado', 'Capturado'), ('de cria', 'De Cría'), ('capturado en agua dulce', 'Capturado en agua dulce')], max_length=25, null=True, verbose_name='Método de producción')),
                ('arte', models.CharField(blank=True, choices=[('raños', 'RAÑOS'), ('nasas', 'NASAS Y TRAMPAS'), ('buceo', 'BUCEO'), ('otros', 'OTROS')], max_length=30, null=True, verbose_name='Arte de Pesca')),
                ('doc_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', related_query_name='entrada', to='bivalvos.docregistro')),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', related_query_name='entrada', to='especies.especies')),
                ('piscina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='piscinas.piscinas')),
            ],
            options={
                'verbose_name': 'Entrada bivalvos depuración',
                'verbose_name_plural': 'Entradas bivalvos depuración',
                'ordering': ['id'],
            },
        ),
    ]
