# Generated by Django 4.0.1 on 2022-01-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fao', models.CharField(max_length=3, verbose_name='Código FAO')),
                ('n_cientifico', models.CharField(max_length=30, verbose_name='Nombre científico')),
                ('n_comercial', models.CharField(max_length=30, verbose_name='Nombre Comercial')),
                ('depuracion', models.BooleanField(default=False, verbose_name='¿Depuración en Mercamaris?')),
            ],
            options={
                'verbose_name': 'Especie',
                'verbose_name_plural': 'Especies',
            },
        ),
    ]
