# Generated by Django 4.0.1 on 2022-01-08 17:34

import apps.especies.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especies',
            name='fao',
            field=apps.especies.models.UpperCaseCharField(max_length=3, verbose_name='Código FAO'),
        ),
    ]
