# Generated by Django 4.0.1 on 2022-01-10 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especies', '0002_alter_especies_fao'),
    ]

    operations = [
        migrations.AddField(
            model_name='especies',
            name='tipo',
            field=models.CharField(choices=[('bivalvos', 'Bivalvos'), ('crustaceos', 'Crustáceos')], default='bivalvos', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='especies',
            name='n_comercial',
            field=models.CharField(max_length=30, verbose_name='Nombre comercial'),
        ),
    ]
