# Generated by Django 4.0.1 on 2022-01-13 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especies', '0003_especies_tipo_alter_especies_n_comercial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especies',
            options={'ordering': ['n_comercial'], 'verbose_name': 'Especie', 'verbose_name_plural': 'Especies'},
        ),
    ]
